# Generated by Django 3.0.8 on 2020-07-20 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='articles.Category', verbose_name='category_id'),
        ),
    ]
