# Generated by Django 3.0.8 on 2020-08-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(max_length=50, verbose_name='fname')),
                ('lname', models.CharField(max_length=50, verbose_name='lname')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=100, verbose_name='phone')),
                ('amount', models.CharField(max_length=50, verbose_name='amount')),
                ('done', models.BooleanField(default=False, verbose_name='paymet')),
                ('order_id', models.CharField(default='', max_length=50, verbose_name='order_id')),
            ],
            options={
                'verbose_name': 'donation',
                'verbose_name_plural': 'donations',
                'db_table': 'donation',
            },
        ),
        migrations.AlterField(
            model_name='articles',
            name='realease',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
