# Generated by Django 3.0.8 on 2020-08-09 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlescount',
            options={'verbose_name': 'ArticleCount', 'verbose_name_plural': 'ArticleCount'},
        ),
    ]
