# Generated by Django 3.0.8 on 2020-08-02 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20200801_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='done',
            new_name='status',
        ),
    ]
