# Generated by Django 3.0.8 on 2020-08-07 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200806_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('counter', models.IntegerField(verbose_name='count')),
                ('article', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='articles.Articles', verbose_name='Articles')),
            ],
            options={
                'verbose_name': 'ArticleCount',
                'verbose_name_plural': 'ArticleCounts',
                'db_table': 'articlescount',
            },
        ),
    ]
