# Generated by Django 3.0.8 on 2020-07-12 05:51

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0002_auto_20200710_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, default=' '),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(upload_to='category'),
        ),
    ]
