# Generated by Django 3.0.8 on 2020-07-13 07:03

import datetime
from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0003_auto_20200712_1121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2020, 7, 13, 12, 33, 50, 945367), unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=image_optimizer.fields.OptimizedImageField(default='def.png', upload_to='category'),
        ),
    ]
