# Generated by Django 3.0.8 on 2020-07-13 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0006_auto_20200713_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='category',
            field=models.ForeignKey(default=34, on_delete=django.db.models.deletion.CASCADE, to='superadmin.Category', verbose_name='category_id'),
        ),
    ]
