# Generated by Django 3.0.8 on 2020-07-14 08:26

from django.db import migrations, models
import image_optimizer.fields


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0007_articles_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', image_optimizer.fields.OptimizedImageField(upload_to='category')),
                ('created_on', models.DateTimeField(auto_now=True)),
                ('added_by', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'ArticleImage',
                'verbose_name_plural': 'ArticleImages',
                'db_table': 'articleimage',
            },
        ),
    ]
