# Generated by Django 3.0.8 on 2020-07-16 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0009_auto_20200715_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='content',
            field=models.TextField(default='hyy'),
        ),
    ]
