# Generated by Django 3.0.8 on 2020-07-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0018_auto_20200717_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='articles',
            name='is_active',
            field=models.NullBooleanField(default=True),
        ),
    ]
