# Generated by Django 3.0.8 on 2020-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0019_auto_20200717_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
