# Generated by Django 3.0.8 on 2020-07-17 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0020_auto_20200717_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='realease',
            field=models.DateTimeField(),
        ),
    ]
