# Generated by Django 3.0.8 on 2020-07-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0021_auto_20200717_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='subtitle',
            field=models.CharField(blank=True, default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='articles',
            name='title',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
