# Generated by Django 3.0.8 on 2020-07-20 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('superadmin', '0022_auto_20200718_1014'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ArticleImages',
        ),
        migrations.DeleteModel(
            name='Articles',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
